name: Build and Run Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      ## checks out our project source code
      - uses: actions/checkout@v2

      - name: Run App
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: docker-compose up -d
